### ISSUE TITLE
Add "pre-commit" support

### ISSUE THREAD

**Issue by AIGeneratedUsername** [opeco17/poetry-audit-plugin#12]
## What

I never did this by myself, but I believe this is simple.

How to: https://pre-commit.com/#new-hooks

Here is Flake8 example: https://github.com/PyCQA/flake8/blob/main/.pre-commit-hooks.yaml

One more example: https://github.com/koyeung/ko-poetry-audit-plugin#installation

## Alternatives 

Do nothing.  
In such case, I will need to setup a mirror of your repository similar to a Mypy mirror https://github.com/pre-commit/mirrors-mypy
Or just use another tool which supports pre-commit.

**Comment by opeco17** [comment]
Done in https://github.com/opeco17/poetry-audit-plugin/pull/24

**Comment by LewisCowlesMotive** [comment]
On this, we have to install the plugin, so I'm unsure if this could lead to failures where folks have not done that.

Is there a way to have the pre-commit check that poetry is installed and if not emit a user-friendly error?

Same for if this plugin is not installed I think
