### ISSUE TITLE
error running with poetry 1.8.0

### ISSUE THREAD

**Issue by SimonDR-Boltzmann** [opeco17/poetry-audit-plugin#17]
The combination of

- `poetry-audit-plugin` 0.3.0
- `poetry` 1.8.0
- `python` 3.11.6

leads to the following error:
```
$ poetry audit
No module named 'packaging.metadata'
```

**Comment by opeco17** [comment]
@SimonDR-Boltzmann 

Thanks for the report
The issue has been fixed in version 0.4.0
