### ISSUE TITLE
`poetry audit` fails on poetry version 1.2.0b3

### ISSUE THREAD

**Issue by zwade** [opeco17/poetry-audit-plugin#2]
## Issue

`poetry audit` fails due to:

```
Locker.locked_repository() takes 1 positional argument but 2 were given
```

Patching line 26 of `command.py` to remove the argument to `self.poetry.locker.locked_repository` resolves the issues.

## Versions

Python: 3.10.0
Poetry: 1.2.0b3
Poetry Audit Plugin: 0.1.1
OS: Mac OS 12.1

**Comment by zwade** [comment]
It looks like circa poetry 1.2.0b2 the `with_dev_reqs` option was removed: https://github.com/python-poetry/poetry/commit/0c6808ba2700c6a446c40633ed81ee929174a649

Would it be possible to either drop this argument outright, or case on the version of poetry before passing it?

**Comment by opeco17** [comment]
@zwade 
Thank you for reporting the issue and creating PR!
Please let me check it!
